version: '3.7'

services:
  web:
    build: ./
    command: python ./simple_blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./simple_blog/simple_blog/.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=simple_blog.db


volumes:
  postgres: